abstract: Catalyst Plugin for Multiple ConfigLoader
author: Mashiro Funakoshi <masap@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Plugin-ConfigLoader-Multi
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 0
  Catalyst::Plugin::ConfigLoader: 0.17
  Test::More: 0
version: 0.04
